baseURL: https://iowameshnet.github.io/
languageCode: en-us
title: Iowa Mesh

theme: iowamesh

params:
  logo: /images/icon.png
  mapboxToken: pk.eyJ1IjoiZXRoYW5oYXJzdGFkIiwiYSI6ImNtN3Y4YjZkazA4b2cya3B3cGVqdWpnOGIifQ.Lu7fPiHPjQ_bxr4TR33Bjg
  meshmapUrl: https://meshmap.iowamesh.net/

menus:
  main:
    - name: MeshMap
      weight: 10
      url: https://meshmap.iowamesh.net/?zoom=8&lat=41.795770762948315&lng=266.7178868078869

build:
  buildStats:
    enable: true
  cachebusters:
    - source: assets/notwatching/hugo_stats\.json
      target: css
    - source: (postcss|tailwind)\.config\.js
      target: css
module:
  mounts:
    - source: assets
      target: assets
    - disableWatch: true
      source: hugo_stats.json
      target: assets/notwatching/hugo_stats.json
